// ===== Mock Data for MeeLike Seller Prototype =====

import type {
  Seller,
  Worker,
  Team,
  TeamMember,
  StoreService,
  Order,
  OrderItem,
  Job,
  JobClaim,
  WorkerAccount,
  Payout,
} from '@/types';

// ===== MOCK SELLER =====
export const mockSeller: Seller = {
  id: 'seller-1',
  userId: 'user-1',
  displayName: 'จอห์น',
  storeName: 'JohnBoost',
  storeSlug: 'johnboost',
  avatar: '/avatars/seller-1.jpg',
  bio: 'รับปั้มยอด Facebook, Instagram, TikTok คุณภาพดี ราคาถูก',
  lineId: '@johnboost',
  phone: '081-234-5678',
  email: 'john@example.com',
  plan: 'pro',
  planExpiresAt: '2025-02-28',
  balance: 2450,
  totalOrders: 156,
  totalRevenue: 45680,
  rating: 4.8,
  ratingCount: 89,
  storeTheme: 'meelike',
  isActive: true,
  isVerified: true,
  createdAt: '2024-01-15',
  updatedAt: '2024-12-30',
};

// ===== MOCK WORKER =====
export const mockWorker: Worker = {
  id: 'worker-1',
  userId: 'user-2',
  displayName: 'นุ่น',
  avatar: '/avatars/worker-1.jpg',
  bio: 'รับงานกดไลค์ คอมเม้น ตลอด 24 ชม.',
  lineId: 'nune_work',
  phone: '089-876-5432',
  bankName: 'กสิกรไทย',
  bankAccount: '123-4-56789-0',
  bankAccountName: 'นางสาวนุ่น ทำงาน',
  promptPayId: '0898765432',
  totalJobs: 234,
  totalEarned: 8750,
  completionRate: 98.5,
  rating: 4.9,
  ratingCount: 156,
  level: 'gold',
  totalJobsCompleted: 234,
  pendingBalance: 127.50,
  availableBalance: 320.00,
  isActive: true,
  isBanned: false,
  teamIds: ['team-1', 'team-2'],
  dailyStreak: 7,
  monthlyJobsTarget: 100,
  monthlyJobsCompleted: 67,
  createdAt: '2024-03-01',
  lastActiveAt: '2024-12-30',
};

// ===== MOCK WORKERS LIST =====
export const mockWorkers: Worker[] = [
  mockWorker,
  {
    id: 'worker-2',
    userId: 'user-3',
    displayName: 'เบส',
    avatar: '/avatars/worker-2.jpg',
    bio: 'ยินดีรับงานทุกชนิด',
    lineId: 'bass_sm',
    totalJobs: 89,
    totalEarned: 3200,
    completionRate: 95.0,
    rating: 4.7,
    ratingCount: 65,
    level: 'silver',
    totalJobsCompleted: 89,
    pendingBalance: 45.00,
    availableBalance: 180.00,
    isActive: true,
    isBanned: false,
    teamIds: ['team-1'],
    dailyStreak: 3,
    monthlyJobsTarget: 50,
    monthlyJobsCompleted: 28,
    createdAt: '2024-06-15',
    lastActiveAt: '2024-12-30',
  },
  {
    id: 'worker-3',
    userId: 'user-4',
    displayName: 'มิ้นท์',
    lineId: 'mint_work123',
    totalJobs: 456,
    totalEarned: 18500,
    completionRate: 99.2,
    rating: 5.0,
    ratingCount: 320,
    level: 'platinum',
    totalJobsCompleted: 456,
    pendingBalance: 250.00,
    availableBalance: 890.00,
    isActive: true,
    isBanned: false,
    teamIds: ['team-1', 'team-2', 'team-3'],
    dailyStreak: 15,
    monthlyJobsTarget: 150,
    monthlyJobsCompleted: 112,
    createdAt: '2024-01-05',
    lastActiveAt: '2024-12-30',
  },
];

// ===== MOCK TEAM =====
export const mockTeam: Team = {
  id: 'team-1',
  sellerId: 'seller-1',
  name: 'ทีม JohnBoost',
  description: 'ทีมงานคุณภาพ ทำงานรวดเร็ว จ่ายตรงเวลา',
  avatar: '/avatars/team-1.jpg',
  rules: [
    'ทำงานให้เสร็จภายใน 24 ชม.',
    'ห้ามใช้ Bot',
    'ส่งหลักฐานทุกครั้ง',
  ],
  inviteCode: 'JOHN2024',
  requireApproval: false,
  isPublic: true,
  isRecruiting: true,
  recruitingMessage: 'รับสมาชิกใหม่! มีงานให้ทำทุกวัน',
  memberCount: 45,
  activeJobCount: 12,
  totalJobsCompleted: 1256,
  isActive: true,
  createdAt: '2024-01-15',
  updatedAt: '2024-12-30',
};

// ===== MOCK TEAMS LIST =====
export const mockTeams: Team[] = [
  mockTeam,
  {
    id: 'team-2',
    sellerId: 'seller-2',
    name: 'ทีม SocialPro',
    description: 'รับงาน Facebook Instagram',
    inviteCode: 'SOCIAL99',
    requireApproval: true,
    isPublic: true,
    isRecruiting: true,
    recruitingMessage: 'หาคนทำงาน FB IG',
    memberCount: 28,
    activeJobCount: 8,
    totalJobsCompleted: 890,
    isActive: true,
    createdAt: '2024-02-20',
    updatedAt: '2024-12-30',
  },
  {
    id: 'team-3',
    sellerId: 'seller-3',
    name: 'ทีม TikTok Master',
    description: 'เฉพาะงาน TikTok',
    inviteCode: 'TIKTOK55',
    requireApproval: false,
    isPublic: false,
    isRecruiting: false,
    memberCount: 15,
    activeJobCount: 5,
    totalJobsCompleted: 456,
    isActive: true,
    createdAt: '2024-04-10',
    updatedAt: '2024-12-30',
  },
];

// ===== MOCK TEAM MEMBERS =====
export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm-1',
    teamId: 'team-1',
    workerId: 'worker-1',
    status: 'active',
    role: 'member',
    jobsCompleted: 120,
    totalEarned: 4500,
    rating: 4.9,
    ratingCount: 98,
    joinedAt: '2024-03-01',
    lastActiveAt: '2024-12-30',
  },
  {
    id: 'tm-2',
    teamId: 'team-1',
    workerId: 'worker-2',
    status: 'active',
    role: 'member',
    jobsCompleted: 45,
    totalEarned: 1680,
    rating: 4.7,
    ratingCount: 32,
    joinedAt: '2024-06-20',
    lastActiveAt: '2024-12-30',
  },
  {
    id: 'tm-3',
    teamId: 'team-1',
    workerId: 'worker-3',
    status: 'active',
    role: 'admin',
    jobsCompleted: 200,
    totalEarned: 8200,
    rating: 5.0,
    ratingCount: 180,
    joinedAt: '2024-01-20',
    lastActiveAt: '2024-12-30',
  },
];

// ===== MOCK SERVICES =====
export const mockServices: StoreService[] = [
  {
    id: 'svc-1',
    sellerId: 'seller-1',
    name: 'ไลค์ Facebook (Bot)',
    description: 'ไลค์โพสต์ Facebook รวดเร็ว ภายใน 1 ชม.',
    category: 'facebook',
    type: 'like',
    serviceType: 'bot',
    costPrice: 0.08,
    sellPrice: 0.15,
    minQuantity: 100,
    maxQuantity: 10000,
    meelikeServiceId: 'ml-fb-like-001',
    isActive: true,
    orderCount: 234,
    createdAt: '2024-01-15',
    updatedAt: '2024-12-30',
  },
  {
    id: 'svc-2',
    sellerId: 'seller-1',
    name: 'Follow Instagram (คนจริง)',
    description: 'Follow บัญชี Instagram จากคนไทยจริง 100%',
    category: 'instagram',
    type: 'follow',
    serviceType: 'human',
    costPrice: 0.30,
    sellPrice: 0.80,
    minQuantity: 50,
    maxQuantity: 1000,
    estimatedTime: '24-48 ชม.',
    isActive: true,
    orderCount: 89,
    createdAt: '2024-01-15',
    updatedAt: '2024-12-30',
  },
  {
    id: 'svc-3',
    sellerId: 'seller-1',
    name: 'คอมเม้น Facebook (คนจริง)',
    description: 'คอมเม้นข้อความตามที่กำหนด จากคนไทยจริง',
    category: 'facebook',
    type: 'comment',
    serviceType: 'human',
    costPrice: 0.50,
    sellPrice: 1.50,
    minQuantity: 10,
    maxQuantity: 500,
    estimatedTime: '24-72 ชม.',
    isActive: true,
    orderCount: 56,
    createdAt: '2024-02-01',
    updatedAt: '2024-12-30',
  },
  {
    id: 'svc-4',
    sellerId: 'seller-1',
    name: 'Follow TikTok (Bot)',
    description: 'เพิ่มผู้ติดตาม TikTok รวดเร็ว',
    category: 'tiktok',
    type: 'follow',
    serviceType: 'bot',
    costPrice: 0.10,
    sellPrice: 0.25,
    minQuantity: 100,
    maxQuantity: 50000,
    meelikeServiceId: 'ml-tt-follow-001',
    isActive: true,
    orderCount: 178,
    createdAt: '2024-03-15',
    updatedAt: '2024-12-30',
  },
  {
    id: 'svc-5',
    sellerId: 'seller-1',
    name: 'View YouTube (Bot)',
    description: 'เพิ่มยอดวิว YouTube',
    category: 'youtube',
    type: 'view',
    serviceType: 'bot',
    costPrice: 0.05,
    sellPrice: 0.12,
    minQuantity: 500,
    maxQuantity: 100000,
    meelikeServiceId: 'ml-yt-view-001',
    isActive: true,
    orderCount: 67,
    createdAt: '2024-04-01',
    updatedAt: '2024-12-30',
  },
];

// ===== MOCK ORDERS =====
export const mockOrders: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'ORD-2024-001',
    sellerId: 'seller-1',
    customer: {
      name: 'คุณสมชาย',
      contactType: 'line',
      contactValue: '@somchai_shop',
      note: 'ต้องการด่วนครับ',
    },
    items: [],
    subtotal: 385,
    discount: 0,
    total: 385,
    totalCost: 165,
    totalProfit: 220,
    paymentStatus: 'paid',
    paidAt: '2024-12-30T10:30:00',
    status: 'processing',
    progress: 45,
    trackingUrl: 'https://seller.meelike.com/track/ORD-2024-001',
    createdAt: '2024-12-30T10:00:00',
    updatedAt: '2024-12-30T12:00:00',
    confirmedAt: '2024-12-30T10:35:00',
  },
  {
    id: 'order-2',
    orderNumber: 'ORD-2024-002',
    sellerId: 'seller-1',
    customer: {
      name: 'ร้านขายเสื้อผ้า ABC',
      contactType: 'facebook',
      contactValue: 'fb.com/abcshop',
    },
    items: [],
    subtotal: 1200,
    discount: 100,
    total: 1100,
    totalCost: 480,
    totalProfit: 620,
    paymentStatus: 'paid',
    status: 'completed',
    progress: 100,
    trackingUrl: 'https://seller.meelike.com/track/ORD-2024-002',
    createdAt: '2024-12-29T14:00:00',
    updatedAt: '2024-12-30T08:00:00',
    completedAt: '2024-12-30T08:00:00',
  },
  {
    id: 'order-3',
    orderNumber: 'ORD-2024-003',
    sellerId: 'seller-1',
    customer: {
      name: 'คุณแอน',
      contactType: 'phone',
      contactValue: '081-111-2222',
    },
    items: [],
    subtotal: 250,
    discount: 0,
    total: 250,
    totalCost: 100,
    totalProfit: 150,
    paymentStatus: 'pending',
    status: 'pending',
    progress: 0,
    trackingUrl: 'https://seller.meelike.com/track/ORD-2024-003',
    createdAt: '2024-12-30T15:00:00',
    updatedAt: '2024-12-30T15:00:00',
  },
];

// ===== MOCK ORDER ITEMS =====
export const mockOrderItems: OrderItem[] = [
  {
    id: 'item-1',
    orderId: 'order-1',
    serviceId: 'svc-1',
    serviceName: 'ไลค์ FB (Bot)',
    serviceType: 'bot',
    platform: 'facebook',
    type: 'like',
    targetUrl: 'https://facebook.com/post/xxx',
    quantity: 1000,
    unitPrice: 0.15,
    subtotal: 150,
    costPerUnit: 0.08,
    totalCost: 80,
    profit: 70,
    profitPercent: 87.5,
    status: 'completed',
    progress: 100,
    completedQuantity: 1000,
    meelikeOrderId: 'ml-123456',
    completedAt: '2024-12-30T11:00:00',
  },
  {
    id: 'item-2',
    orderId: 'order-1',
    serviceId: 'svc-3',
    serviceName: 'คอมเม้น FB (คนจริง)',
    serviceType: 'human',
    platform: 'facebook',
    type: 'comment',
    targetUrl: 'https://facebook.com/post/xxx',
    quantity: 50,
    commentTemplates: ['สินค้าดีมากครับ', 'แนะนำเลย', 'ชอบมากค่ะ'],
    unitPrice: 1.50,
    subtotal: 75,
    costPerUnit: 0.50,
    totalCost: 25,
    profit: 50,
    profitPercent: 200,
    status: 'processing',
    progress: 30,
    completedQuantity: 15,
    jobId: 'job-1',
    startedAt: '2024-12-30T11:30:00',
  },
  {
    id: 'item-3',
    orderId: 'order-1',
    serviceId: 'svc-2',
    serviceName: 'Follow IG (คนจริง)',
    serviceType: 'human',
    platform: 'instagram',
    type: 'follow',
    targetUrl: 'https://instagram.com/somchai_shop',
    quantity: 200,
    unitPrice: 0.80,
    subtotal: 160,
    costPerUnit: 0.30,
    totalCost: 60,
    profit: 100,
    profitPercent: 166.7,
    status: 'pending',
    progress: 0,
    completedQuantity: 0,
  },
];

// ===== MOCK JOBS =====
export const mockJobs: Job[] = [
  {
    id: 'job-1',
    sellerId: 'seller-1',
    orderId: 'order-1',
    orderItemId: 'item-2',
    title: 'คอมเม้น Facebook - ร้านคุณสมชาย',
    type: 'comment',
    platform: 'facebook',
    targetUrl: 'https://facebook.com/post/xxx',
    targetQuantity: 50,
    pricePerUnit: 0.50,
    requirements: 'คอมเม้นภาษาไทย ดูธรรมชาติ',
    commentTemplates: ['สินค้าดีมากครับ', 'แนะนำเลย', 'ชอบมากค่ะ'],
    teamId: 'team-1',
    visibility: 'all_members',
    status: 'in_progress',
    claimedQuantity: 35,
    completedQuantity: 15,
    createdAt: '2024-12-30T11:30:00',
    updatedAt: '2024-12-30T14:00:00',
  },
  {
    id: 'job-2',
    sellerId: 'seller-1',
    title: 'Follow Instagram - ร้านเสื้อผ้า',
    type: 'follow',
    platform: 'instagram',
    targetUrl: 'https://instagram.com/fashion_shop',
    targetQuantity: 100,
    pricePerUnit: 0.30,
    requirements: 'บัญชีต้องมีโพสต์อย่างน้อย 5 โพสต์',
    teamId: 'team-1',
    visibility: 'all_members',
    minLevelRequired: 'silver',
    status: 'open',
    claimedQuantity: 20,
    completedQuantity: 0,
    createdAt: '2024-12-30T09:00:00',
    updatedAt: '2024-12-30T09:00:00',
  },
  {
    id: 'job-3',
    sellerId: 'seller-1',
    title: 'ไลค์ TikTok',
    type: 'like',
    platform: 'tiktok',
    targetUrl: 'https://tiktok.com/@user/video/xxx',
    targetQuantity: 500,
    pricePerUnit: 0.15,
    teamId: 'team-1',
    visibility: 'all_members',
    status: 'completed',
    claimedQuantity: 500,
    completedQuantity: 500,
    createdAt: '2024-12-29T10:00:00',
    updatedAt: '2024-12-29T18:00:00',
    completedAt: '2024-12-29T18:00:00',
  },
];

// ===== MOCK JOB CLAIMS =====
export const mockJobClaims: JobClaim[] = [
  {
    id: 'claim-1',
    jobId: 'job-1',
    workerId: 'worker-1',
    workerAccountId: 'wa-1',
    quantity: 10,
    earnAmount: 5.00,
    status: 'approved',
    submittedAt: '2024-12-30T12:00:00',
    proofUrls: ['/proofs/claim-1-1.jpg'],
    actualQuantity: 10,
    reviewedAt: '2024-12-30T12:30:00',
    sellerRating: 5,
    createdAt: '2024-12-30T11:30:00',
    updatedAt: '2024-12-30T12:30:00',
  },
  {
    id: 'claim-2',
    jobId: 'job-1',
    workerId: 'worker-2',
    workerAccountId: 'wa-2',
    quantity: 5,
    earnAmount: 2.50,
    status: 'submitted',
    submittedAt: '2024-12-30T13:00:00',
    proofUrls: ['/proofs/claim-2-1.jpg'],
    actualQuantity: 5,
    createdAt: '2024-12-30T12:00:00',
    updatedAt: '2024-12-30T13:00:00',
  },
  {
    id: 'claim-3',
    jobId: 'job-2',
    workerId: 'worker-1',
    workerAccountId: 'wa-1',
    quantity: 20,
    earnAmount: 6.00,
    status: 'claimed',
    createdAt: '2024-12-30T10:00:00',
    updatedAt: '2024-12-30T10:00:00',
  },
];

// ===== MOCK WORKER ACCOUNTS =====
export const mockWorkerAccounts: WorkerAccount[] = [
  {
    id: 'wa-1',
    workerId: 'worker-1',
    platform: 'facebook',
    username: 'nune.work',
    profileUrl: 'https://facebook.com/nune.work',
    screenshotUrl: '/screenshots/wa-1.jpg',
    verificationStatus: 'verified',
    verifiedAt: '2024-03-05',
    verifiedBy: 'ai',
    aiResult: {
      passed: true,
      confidence: 0.95,
      hasProfilePicture: true,
      detectedFollowers: 450,
      usernameMatch: true,
      notes: 'บัญชีผ่านการตรวจสอบอัตโนมัติ',
    },
    followers: 450,
    profilePictureExists: true,
    isActive: true,
    jobsCompleted: 120,
    createdAt: '2024-03-01',
    updatedAt: '2024-12-30',
  },
  {
    id: 'wa-2',
    workerId: 'worker-1',
    platform: 'instagram',
    username: 'nune_work',
    profileUrl: 'https://instagram.com/nune_work',
    screenshotUrl: '/screenshots/wa-2.jpg',
    verificationStatus: 'verified',
    verifiedBy: 'admin',
    followers: 280,
    profilePictureExists: true,
    isActive: true,
    jobsCompleted: 85,
    createdAt: '2024-03-10',
    updatedAt: '2024-12-30',
  },
  {
    id: 'wa-3',
    workerId: 'worker-2',
    platform: 'facebook',
    username: 'bass.social',
    profileUrl: 'https://facebook.com/bass.social',
    screenshotUrl: '/screenshots/wa-3.jpg',
    verificationStatus: 'pending',
    followers: 150,
    profilePictureExists: true,
    isActive: false,
    jobsCompleted: 0,
    createdAt: '2024-12-30',
    updatedAt: '2024-12-30',
  },
];

// ===== MOCK PAYOUTS =====
export const mockPayouts: Payout[] = [
  {
    id: 'payout-1',
    workerId: 'worker-1',
    requestedAmount: 500,
    feeAmount: 10,
    feePercent: 2,
    netAmount: 490,
    method: 'promptpay',
    promptpayNumber: '0898765432',
    status: 'completed',
    transferredAt: '2024-12-29T14:00:00',
    bankRefNumber: 'REF123456',
    createdAt: '2024-12-29T10:00:00',
    updatedAt: '2024-12-29T14:00:00',
  },
  {
    id: 'payout-2',
    workerId: 'worker-1',
    requestedAmount: 200,
    feeAmount: 4,
    feePercent: 2,
    netAmount: 196,
    method: 'bank_transfer',
    bankCode: 'KBANK',
    bankAccountNumber: '123-4-56789-0',
    bankAccountName: 'นางสาวนุ่น ทำงาน',
    status: 'pending',
    createdAt: '2024-12-30T09:00:00',
    updatedAt: '2024-12-30T09:00:00',
  },
];

// ===== STATS SUMMARY =====
export const mockSellerStats = {
  todayOrders: 5,
  todayRevenue: 1250,
  pendingOrders: 3,
  processingOrders: 8,
  pendingReviews: 5,
  activeJobs: 12,
  teamMembers: 45,
  monthlyOrders: 156,
  monthlyRevenue: 45680,
};

export const mockWorkerStats = {
  availableJobs: 15,
  myActiveJobs: 3,
  pendingReview: 2,
  todayEarnings: 45.50,
  weeklyEarnings: 320.00,
  monthlyEarnings: 1250.00,
  dailyStreak: 7,
  currentLevel: 'gold' as const,
  nextLevelProgress: 72,
};

